# Generated by Django 4.2.1 on 2024-08-09 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("raffle", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("raffle", "ticket_number")},
        ),
        migrations.AddField(
            model_name="raffle",
            name="prizes",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="ticket",
            name="is_winner",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="winner",
            name="raffle",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="raffle.raffle",
            ),
        ),
        migrations.AlterField(
            model_name="winner",
            name="prize",
            field=models.JSONField(),
        ),
        migrations.DeleteModel(
            name="Prize",
        ),
    ]
