# Generated by Django 4.2.1 on 2024-08-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffle", "0006_alter_ticket_ticket_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="raffle",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
