# Generated by Django 4.2.1 on 2024-08-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffle", "0010_alter_ticket_verification_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="is_winner",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="verification_code",
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
    ]
