# Generated by Django 4.2.1 on 2024-08-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffle", "0009_alter_raffle_name_alter_ticket_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="verification_code",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
