# Generated by Django 4.2.1 on 2024-08-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("raffle", "0011_alter_ticket_is_winner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="verification_code",
            field=models.CharField(
                blank=True, editable=False, max_length=128, null=True, unique=True
            ),
        ),
    ]
